apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels: # These labels are deployment labels
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:  # These labels are used to find the pods
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # These labels are pod labels
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: gokul0307/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
---
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 #container port