FROM mysql:5.7
# ENV MYSQL_ROOT_PASSWORD=RoboShop@1 \
#     MYSQL_DATABASE=cities \
#     MYSQL_USER=shipping \
#     MYSQL_PASSWORD=RoboShop@1
# Kepping above one in configmap
COPY scripts/* /docker-entrypoint-initdb.d


