apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
---  
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
type: Opaque
data:
  username: 
  password: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: # These labels are deployment labels
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:  # These labels are used to find the pods
      app: mysql
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # These labels are pod labels
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: gokul0307/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql    
---
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 #container port